### ISSUE TITLE
haddock panic on travis: undefined symbol: __gxx_personality_v0

### ISSUE THREAD

**Issue by basvandijk** [LumiGuide/haskell-opencv#108] opened 2018-01-22 08:05 UTC
After the fix for https://github.com/LumiGuide/haskell-opencv/issues/104 travis is *almost* able to build the whole project. Unfortunately the build fails [in the end](https://travis-ci.org/LumiGuide/haskell-opencv/jobs/331631917#L2690
) while running haddock: 

```
    haddock: panic! (the 'impossible' happened)
      (GHC version 8.2.2 for x86_64-unknown-linux):
    	Loading temp shared object failed: /tmp/ghc25214_0/libghc_252.so: 
          undefined symbol: __gxx_personality_v0
```

Note that this error only occurs when building the project using `stack`. With `cabal-install` this doesn't happen.

The following seems related:
https://stackoverflow.com/questions/203548/undefined-symbol-gxx-personality-v0-on-link

**Comment by roelvandijk** [comment] 2018-01-22 08:57
Duplicate of #107

**Closed by roelvandijk** 2018-01-22 08:57 UTC
Labels: duplicate
